Repository kasperpeulen/simply-effect, pull requests merged in 2024-04, with the labels that each got.

#1 Implement effect
  .github/workflows/release.yml
  .gitignore
  README.md
  index.test.ts
  index.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
  vitest.config.ts
Labels: enhancement, patch

#2 Update docs
  README.md
Labels: documentation, patch

#3 Update description
  README.md
  package.json
Labels: documentation, patch

#4 improve readme
  README.md
Labels: documentation, patch

#5 Wrap in backtikcs
  README.md
Labels: documentation, patch

#6 Fix dts file location
  package.json
Labels: bug, patch
